### ISSUE TITLE
Con qué tipo de datos hay que hacer las pruebas unitarias

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/tipi-extract-topics#2]
Datos: Fichero de datos (_data_reference_)

**Comment by xaviuzz** [comment]
datos en pruebas unitarias no lo acbo de ver, deberiamos poder probar solo con inputs, sin necesidad de datos
En pruebas de integracion y de aceptacion... los datos tienen que venir de una 'fixture' que controlamos y que es pristina antes de cada prueba.

**Comment by pr3ssh** [comment]
Entiendo lo que me dices (sobre la no necesidad por naturaleza de datos en test unitarios). Aun asi _creo_ que mucho código que tengo aqui en este proyecto no funciona independientemente sin datos (en este caso sin los excels de datos).

Ok a lo de las fixtures. Creo que tendré en tal caso que hacer test de integración/aceptación.
